name: Release
on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    build:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: install
              run: npm i

            - name: build
              run: npm run build

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      main.js
                      manifest.json
                      styles.css
                  draft: false
                  prerelease: false
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
